import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavbarDemo } from "./navbar/page";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS Routing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
